global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files: []

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8000']
    metrics_path: '/metrics'
    scrape_interval: 15s

  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:8001']
    metrics_path: '/metrics'
    scrape_interval: 15s

  - job_name: 'event-service'
    static_configs:
      - targets: ['event-service:8002']
    metrics_path: '/metrics'
    scrape_interval: 15s

  - job_name: 'nlp-service'
    static_configs:
      - targets: ['nlp-service:8003']
    metrics_path: '/metrics'
    scrape_interval: 15s

  - job_name: 'profile-service'
    static_configs:
      - targets: ['profile-service:8004']
    metrics_path: '/metrics'
    scrape_interval: 15s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
